# Generated by Django 2.0.2 on 2020-03-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userselection',
            name='time_elapsed',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='esrule',
            name='Striggers',
            field=models.ManyToManyField(blank=True, to='backend.Trigger'),
        ),
    ]
