FROM ubuntu:xenial

ARG datafile

RUN apt update && apt install -y python-software-properties software-properties-common postgresql-9.5 postgresql-client-9.5 postgresql-contrib-9.5
RUN chown -R postgres:postgres /var/lib/postgresql/9.5/main

USER postgres
RUN /etc/init.d/postgresql start
RUN echo "host all  all    0.0.0.0/0  md5" >> /etc/postgresql/9.5/main/pg_hba.conf
RUN echo "listen_addresses='*'" >> /etc/postgresql/9.5/main/postgresql.conf
EXPOSE 5432

COPY --chown=postgres $datafile /home/postgres/backup.sql
COPY --chown=postgres ./scripts/init-db.sh /home/postgres/

CMD ["/usr/lib/postgresql/9.5/bin/postgres", "-D", "/var/lib/postgresql/9.5/main", "-c", "config_file=/etc/postgresql/9.5/main/postgresql.conf"]
