from django.contrib import admin
import backend.models as m
# Register your models here.

admin.site.register(m.Channel)
admin.site.register(m.Capability)
admin.site.register(m.Parameter)
admin.site.register(m.SetParam)
admin.site.register(m.SetParamOpt)
admin.site.register(m.RangeParam)
admin.site.register(m.BinParam)
admin.site.register(m.ColorParam)
admin.site.register(m.TimeParam)
admin.site.register(m.DurationParam)
admin.site.register(m.InputParam)
admin.site.register(m.MetaParam)
admin.site.register(m.ParVal)
admin.site.register(m.Condition)
admin.site.register(m.Device)
admin.site.register(m.State)
admin.site.register(m.Trigger)
admin.site.register(m.Rule)
admin.site.register(m.ESRule)
admin.site.register(m.SSRule)
admin.site.register(m.SafetyProp)
admin.site.register(m.SP1)
admin.site.register(m.SP2)
admin.site.register(m.SP3)
admin.site.register(m.StateLog)
admin.site.register(m.UserSelection)
admin.site.register(m.ESRuleMeta)
admin.site.register(m.UserStudyTapSet)
admin.site.register(m.User)